version: '3.8'
services:
  app:
    build:
      context: ./app
    ports:
      - "8000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"